name: angplop
version: 1.0.0+1
publish_to: none
description: Rencanakan, Anggarkan, Wujudkan
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  month_picker_dialog: ^0.4.0
  group_list_view: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_beautiful_popup: ^1.4.0
  hexcolor: any
  logger: any
  flutter_datetime_picker: any
  flutter_flavor: any
  http: 0.13.4
  flutter_svg: any
  google_fonts: any
  flutter_staggered_grid_view: any
  lazy_load_scrollview: any
  intl: any
  get_storage: any
  get: 4.6.1
  flutter_html: ^2.2.1
  flutter_launcher_icons: any
  device_preview: any
  eva_icons_flutter: any
  otp_text_field: ^1.0.0
  flutter_otp_timer: any
  otp_count_down: ^1.0.6
  google_sign_in: any
  rename: ^2.0.1
  url_launcher: any
  path_provider: any
  open_file: any
  pdf: any
  file_picker: any
  currency_text_input_formatter: ^2.1.1
  rounded_loading_button: any
  image_picker: ^0.8.5
  image_cropper: ^1.3.0
  photo_manager: any
  filesize: ^2.0.1
  get_cli: ^1.7.1
  onboarding: ^3.1.0
  flutter: 
    sdk: flutter
  uni_links: ^0.5.1
  flutter_spinkit: ^5.1.0
  flutter_widget_from_html: ^0.8.5

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/iconAngplop.png
  android: true
  ios: true

flutter: 
  fonts: 
    - family: Nexa
      fonts: 
        - asset: assets/fonts/Nexa-Trial-Regular.ttf
        - asset: assets/fonts/Nexa-Trial-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Nexa-Trial-Bold.ttf
          weight: 700
    - family: Nunito
      fonts: 
        - asset: assets/fonts/nunito.regular.ttf
    
  assets: 
    - assets/
  uses-material-design: true

